# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/download-artifact@v2
        with:
          name: jar

      # Runs a single command using the runners shell
      - name: Run a one-line script
      - run: |
          NEW_JAR=$(realpath $(find . -name photonvision\*.jar))
          sudo apt install unzip zip
          curl -sk https://api.github.com/repos/photonvision/photon-pi-gen/releases/tags/v2021.1.4 | grep "browser_download_url.*zip" | cut -d : -f 2,3 | tr -d '"' | wget -qi -
          FILE_NAME=$(ls | grep image_*.zip)
          unzip $FILE_NAME
          IMAGE_FILE=$(ls | grep *.img)
          TMP=$(mktemp -d)
          LOOP=$(sudo losetup --show -fP "${IMAGE_FILE}")
          sudo mount ${LOOP}p2 $TMP
          pushd .
          cd $TMP/opt/photonvision
          ls
          sudo cp $NEW_JAR photonvision.jar
          popd
          sudo umount ${TMP}
          sudo rmdir ${TMP}
          rm $FILE_NAME
          NEW_IMAGE=$(basename "${NEW_JAR/jar/img}")
          mv $IMAGE_FILE $NEW_IMAGE
          zip -r $(basename "${NEW_JAR/jar/zip}") $NEW_IMAGE
          rm $NEW_IMAGE
